#include "uefilib.h"
EGWS CTGAS[] = {
    {EFI_ACPI_TABLE_GUID, u"EFI_ACPI_TABLE_GUID"},
    {ACPI_TABLE_GUID, u"ACPI_TABLE_GUID"},
    {SAL_SYSTEM_TABLE_GUID, u"SAL_SYSTEM_TABLE_GUID"},
    {SMBIOS_TABLE_GUID, u"SMBIOS_TABLE_GUID"},
    {SMBIOS3_TABLE_GUID, u"SMBIOS3_TABLE_GUID"},
    {MPS_TABLE_GUID, u"MPS_TABLE_GUID"},
};